FROM alpine:3.20 AS dl
RUN wget -q https://github.com/apernet/hysteria/releases/download/v2.6.1/hysteria-linux-amd64 -O /usr/local/bin/hy2 && chmod +x /usr/local/bin/hy2

FROM alpine:3.20
COPY --from=dl /usr/local/bin/hy2 /usr/local/bin/hy2
ENTRYPOINT ["/usr/local/bin/hy2"]
